// Zones action types
export const FETCH_ZONES_REQUEST = 'FETCH_ZONES_REQUEST';
export const FETCH_ZONES_SUCCESS = 'FETCH_ZONES_SUCCESS';
export const FETCH_ZONES_FAILURE = 'FETCH_ZONES_FAILURE';

export const FETCH_ZONE_DETAILS_REQUEST = 'FETCH_ZONE_DETAILS_REQUEST';
export const FETCH_ZONE_DETAILS_SUCCESS = 'FETCH_ZONE_DETAILS_SUCCESS';
export const FETCH_ZONE_DETAILS_FAILURE = 'FETCH_ZONE_DETAILS_FAILURE';

export const CREATE_ZONE_REQUEST = 'CREATE_ZONE_REQUEST';
export const CREATE_ZONE_SUCCESS = 'CREATE_ZONE_SUCCESS';
export const CREATE_ZONE_FAILURE = 'CREATE_ZONE_FAILURE';

export const UPDATE_ZONE_REQUEST = 'UPDATE_ZONE_REQUEST';
export const UPDATE_ZONE_SUCCESS = 'UPDATE_ZONE_SUCCESS';
export const UPDATE_ZONE_FAILURE = 'UPDATE_ZONE_FAILURE';

export const DELETE_ZONE_REQUEST = 'DELETE_ZONE_REQUEST';
export const DELETE_ZONE_SUCCESS = 'DELETE_ZONE_SUCCESS';
export const DELETE_ZONE_FAILURE = 'DELETE_ZONE_FAILURE';

export const FETCH_ZONE_DROPDOWN_REQUEST = 'FETCH_ZONE_DROPDOWN_REQUEST';
export const FETCH_ZONE_DROPDOWN_SUCCESS = 'FETCH_ZONE_DROPDOWN_SUCCESS';
export const FETCH_ZONE_DROPDOWN_FAILURE = 'FETCH_ZONE_DROPDOWN_FAILURE';