export const FETCH_ADMIN_REQUEST = "FETCH_ADMIN_REQUEST";
export const FETCH_ADMIN_SUCCESS = "FETCH_ADMIN_SUCCESS";
export const FETCH_ADMIN_FAILURE = "FETCH_ADMIN_FAILURE";

// Fetch Admin by ID
export const FETCH_ADMIN_BY_ID_REQUEST = "FETCH_ADMIN_BY_ID_REQUEST";
export const FETCH_ADMIN_BY_ID_SUCCESS = "FETCH_ADMIN_BY_ID_SUCCESS";
export const FETCH_ADMIN_BY_ID_FAILURE = "FETCH_ADMIN_BY_ID_FAILURE";

// Create Subadmin
export const CREATE_SUBADMIN_REQUEST = "CREATE_SUBADMIN_REQUEST";
export const CREATE_SUBADMIN_SUCCESS = "CREATE_SUBADMIN_SUCCESS";
export const CREATE_SUBADMIN_FAILURE = "CREATE_SUBADMIN_FAILURE";

// Fetch Cluster Dropdown
export const FETCH_CLUSTER_DROPDOWN_REQUEST = "FETCH_CLUSTER_DROPDOWN_REQUEST";
export const FETCH_CLUSTER_DROPDOWN_SUCCESS = "FETCH_CLUSTER_DROPDOWN_SUCCESS";
export const FETCH_CLUSTER_DROPDOWN_FAILURE = "FETCH_CLUSTER_DROPDOWN_FAILURE";

// Fetch Venue Dropdown
export const FETCH_VENUE_DROPDOWN_REQUEST = "FETCH_VENUE_DROPDOWN_REQUEST";
export const FETCH_VENUE_DROPDOWN_SUCCESS = "FETCH_VENUE_DROPDOWN_SUCCESS";
export const FETCH_VENUE_DROPDOWN_FAILURE = "FETCH_VENUE_DROPDOWN_FAILURE";