// Venue action types
export const FETCH_VENUES_REQUEST = 'FETCH_VENUES_REQUEST';
export const FETCH_VENUES_SUCCESS = 'FETCH_VENUES_SUCCESS';
export const FETCH_VENUES_FAILURE = 'FETCH_VENUES_FAILURE';

export const FETCH_VENUE_REQUEST = 'FETCH_VENUE_REQUEST';
export const FETCH_VENUE_SUCCESS = 'FETCH_VENUE_SUCCESS';
export const FETCH_VENUE_FAILURE = 'FETCH_VENUE_FAILURE';

export const CREATE_VENUE_REQUEST = 'CREATE_VENUE_REQUEST';
export const CREATE_VENUE_SUCCESS = 'CREATE_VENUE_SUCCESS';
export const CREATE_VENUE_FAILURE = 'CREATE_VENUE_FAILURE';

export const UPDATE_VENUE_REQUEST = 'UPDATE_VENUE_REQUEST';
export const UPDATE_VENUE_SUCCESS = 'UPDATE_VENUE_SUCCESS';
export const UPDATE_VENUE_FAILURE = 'UPDATE_VENUE_FAILURE';

export const DELETE_VENUE_REQUEST = 'DELETE_VENUE_REQUEST';
export const DELETE_VENUE_SUCCESS = 'DELETE_VENUE_SUCCESS';
export const DELETE_VENUE_FAILURE = 'DELETE_VENUE_FAILURE';

export const DROPDOWN_VENUE = '/dropdown/venue';

export const FETCH_DROPDOWN_VENUES_REQUEST = 'FETCH_DROPDOWN_VENUES_REQUEST';
export const FETCH_DROPDOWN_VENUES_SUCCESS = 'FETCH_DROPDOWN_VENUES_SUCCESS';
export const FETCH_DROPDOWN_VENUES_FAILURE = 'FETCH_DROPDOWN_VENUES_FAILURE';

// Facility action types
export const FETCH_FACILITIES_BY_VENUE_REQUEST = 'FETCH_FACILITIES_BY_VENUE_REQUEST';
export const FETCH_FACILITIES_BY_VENUE_SUCCESS = 'FETCH_FACILITIES_BY_VENUE_SUCCESS';
export const FETCH_FACILITIES_BY_VENUE_FAILURE = 'FETCH_FACILITIES_BY_VENUE_FAILURE';

export const CREATE_FACILITY_REQUEST = 'CREATE_FACILITY_REQUEST';
export const CREATE_FACILITY_SUCCESS = 'CREATE_FACILITY_SUCCESS';
export const CREATE_FACILITY_FAILURE = 'CREATE_FACILITY_FAILURE';

export const UPDATE_FACILITY_REQUEST = 'UPDATE_FACILITY_REQUEST';
export const UPDATE_FACILITY_SUCCESS = 'UPDATE_FACILITY_SUCCESS';
export const UPDATE_FACILITY_FAILURE = 'UPDATE_FACILITY_FAILURE';

export const DELETE_FACILITY_REQUEST = 'DELETE_FACILITY_REQUEST';
export const DELETE_FACILITY_SUCCESS = 'DELETE_FACILITY_SUCCESS';
export const DELETE_FACILITY_FAILURE = 'DELETE_FACILITY_FAILURE';