export const FETCH_CLUSTERS_REQUEST = "FETCH_CLUSTERS_REQUEST";
export const FETCH_CLUSTERS_SUCCESS = "FETCH_CLUSTERS_SUCCESS";
export const FETCH_CLUSTERS_FAILURE = "FETCH_CLUSTERS_FAILURE";

export const FETCH_SINGLE_CLUSTER_REQUEST = "FETCH_SINGLE_CLUSTER_REQUEST";
export const FETCH_SINGLE_CLUSTER_SUCCESS = "FETCH_SINGLE_CLUSTER_SUCCESS";
export const FETCH_SINGLE_CLUSTER_FAILURE = "FETCH_SINGLE_CLUSTER_FAILURE";

export const CREATE_CLUSTER_REQUEST = "CREATE_CLUSTER_REQUEST";
export const CREATE_CLUSTER_SUCCESS = "CREATE_CLUSTER_SUCCESS";
export const CREATE_CLUSTER_FAILURE = "CREATE_CLUSTER_FAILURE";

export const UPDATE_CLUSTER_REQUEST = "UPDATE_CLUSTER_REQUEST";
export const UPDATE_CLUSTER_SUCCESS = "UPDATE_CLUSTER_SUCCESS";
export const UPDATE_CLUSTER_FAILURE = "UPDATE_CLUSTER_FAILURE";

export const DELETE_CLUSTER = "DELETE_CLUSTER";
export const DELETE_CLUSTER_REQUEST = "DELETE_CLUSTER_REQUEST";
export const DELETE_CLUSTER_SUCCESS = "DELETE_CLUSTER_SUCCESS";
export const DELETE_CLUSTER_FAILURE = "DELETE_CLUSTER_FAILURE";

export const FETCH_CLUSTER_DROPDOWN_REQUEST = "FETCH_CLUSTER_DROPDOWN_REQUEST";
export const FETCH_CLUSTER_DROPDOWN_SUCCESS = "FETCH_CLUSTER_DROPDOWN_SUCCESS";
export const FETCH_CLUSTER_DROPDOWN_FAILURE = "FETCH_CLUSTER_DROPDOWN_FAILURE";