export const FACILITY_LOADING = 'FACILITY_LOADING';
export const FACILITY_ERROR = 'FACILITY_ERROR';

export const CREATE_FACILITY_SUCCESS = 'CREATE_FACILITY_SUCCESS';
export const GET_ALL_FACILITIES_SUCCESS = 'GET_ALL_FACILITIES_SUCCESS';
export const GET_SINGLE_FACILITY_SUCCESS = 'GET_SINGLE_FACILITY_SUCCESS';
export const UPDATE_FACILITY_SUCCESS = 'UPDATE_FACILITY_SUCCESS';
export const DELETE_FACILITY_SUCCESS = 'DELETE_FACILITY_SUCCESS';
export const GET_FACILITY_DROPDOWN_SUCCESS = 'GET_FACILITY_DROPDOWN_SUCCESS';

export const RESET_FACILITY_STATE = 'RESET_FACILITY_STATE';
export const RESET_FACILITY_ERROR = 'RESET_FACILITY_ERROR';
export const GET_SPORTS_DROPDOWN_SUCCESS = 'GET_SPORTS_DROPDOWN_SUCCESS';
export const GET_ZONES_BY_FACILITY = "GET_ZONES_BY_FACILITY_SUCCESS";

